### ISSUE TITLE
Step: Update configuration - Go to “Start” button function 

### ISSUE THREAD

**Issue by angeleja** [microsoft/SAPAzureSnooze#1]
Hello, 

I cannot find the Start button in the Tree view of PowerApps studio. 
Can you please give more details on this one? Thank you.

![2020-05-29_15-23-38](https://user-images.githubusercontent.com/54050152/83239723-ed9a4e80-a1ca-11ea-9a4d-26a94595c187.png)

**Comment by sanoop-t** [comment]
Hello, looks like you may not have connected to the SharePoint list. Please go to View data sources and create a new SharePoint connection to the SAP system List. The readme.md file has the instructions.

**Comment by angeleja** [comment]
Thank you
